apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.postgres.example.com
spec:
  group: postgres.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                password:
                  type: string
          required:
            - spec
  scope: Namespaced
  names:
    plural: postgresdatabases
    singular: postgresdatabase
    kind: PostgresDatabase
status:
  storedVersions:
    - v1
